### ISSUE TITLE
Game won't run in IntelliJ

### ISSUE THREAD

**Issue by rc1035** [SEPR-EEP/taxe-game-2#7]
I created a run configuration to run the game (via the DesktopLauncher class) and whenever I attempt to run it I get this error:

> Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
>     at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
> Caused by: java.lang.ExceptionInInitializerError
>     at com.TeamHEC.LocomotionCommotion.LocomotionCommotion.create(LocomotionCommotion.java:45)
>     at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:136)
>     at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
> Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: startMenu/sm_main/smTitle.png

Here is where the path is declared:

``` java
public CustomTexture sm_main_title = new CustomTexture(Gdx.files.internal("startMenu/sm_main/smTitle.png"));
```

Does anyone have the same problem? Or have I simply misconfigured the project somehow? I notice ( ffa39f38ce1265301c071f0386f7c99b6f373659 ) the textures were changed from type Texture to CustomTexture, could this be relevant?

**Comment by AlfioEmanueleFresta** [comment]
@rc1035 you may be trying to run the game from the wrong path. You would need to change your run configuration PATH to be `desktop/`. 

Anyway, if you pull the latest version of the project, you should be able to find a "Master BUILD" configuration for IDEA already there (it is in `.idea/runConfigurations`) - if not, you may need to delete and reload the project. That configuration builds, in order, the core and the desktop application, runs the tests and finally runs the desktop app.

**Comment by kokoff** [comment]
The problem is not in the custom textures. Custom texture is simply a class that extends Texture and is the same as texture in every way except that it applyes a linier filter so non of the png's gets blurred when resizing. You should check if the path is correct.

**Comment by AlfioEmanueleFresta** [comment]
@kokoff is right. The problem is that `startMenu/<...>/<...>.png` is relative to `desktop/` and not to the project directory.

**Comment by rc1035** [comment]
Thanks, that was the issue :)
